# action.yaml
name: "FireTail Github Action"
description: "A Github Action that will upload an API Spec file to the FireTail Platform and perform static analysis on your repository"
inputs:
  FIRETAIL_API_TOKEN:
    description: "Your FireTail API token"
    required: true
  FIRETAIL_API_URL:
    description: "Your FireTail API token"
    required: false
    default: "https://api.saas.eu-west-1.prod.firetail.app"
  CONTEXT:
    required: false
    description: "provides the github context that gets passed with the api call. this allows for determining where the change came from and by which user"
  COLLECTION_UUID:
    description: "UUID of the FireTail API Collection to directly upload the API spec at API_SPEC_LOCATION to"
    required: false
  API_SPEC_LOCATION:
    description: "Path to your OpenAPI/Swagger spec file"
    required: false
  STATIC_ANALYSIS_ROOT_DIR:
    description: "The root directory in your repository to perform static analysis from"
    required: false
    default: "/"
  STATIC_ANALYSIS_LANGUAGES:
    description: "A comma separated list of languages to statically analyse (currently supported are Python, Golang and Javascript)"
    required: false
    default: "Python,Golang,Javascript"
runs:
  using: "docker"
  image: "Dockerfile.githubaction"
