name: Draft Release
run-name: '@${{ github.triggering_actor }}: ${{ github.ref_name }}: ${{ github.event_name }}'

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: firetail-code-repository-scanner

jobs:
  draft-release:
    name: Draft Release

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.25.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Tags From Release Output
        run: |
          NAMESPACE="$(awk '{print(tolower($0))}' <<<${{ github.repository_owner }})"
          cat <<HEREDOC >>${GITHUB_ENV}
          TAG_BASE=${{ env.REGISTRY }}/${NAMESPACE}/${{ env.IMAGE_NAME }}
          PRERELEASE_IMAGE_TAG=${{ steps.draft_release.outputs.tag_name }}-prerelease
          PRERELEASE_LAMBDA_IMAGE_TAG=${{ steps.draft_release.outputs.tag_name }}-lambda-prerelease
          HEREDOC

      - name: Log In to the Container Registry
        run: |
           docker login ${{ env.REGISTRY }} \
            --username ${{ github.actor }} \
            --password-stdin <<<${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Runtime Image
        run: |
          docker build \
            --target runtime \
            --tag ${{ env.TAG_BASE }}:${{ env.PRERELEASE_IMAGE_TAG }} \
            --file build_setup/Dockerfile \
            "${PWD}"
          docker tag ${{ env.TAG_BASE }}:${{ env.PRERELEASE_IMAGE_TAG }} \
            ${{ env.TAG_BASE }}:latest-prerelease
          docker push ${{ env.TAG_BASE }}:${{ env.PRERELEASE_IMAGE_TAG }}
          docker push ${{ env.TAG_BASE }}:latest-prerelease

      - name: Build and Push Lambda Image
        run: |
          docker build \
            --target runtime-lambda \
            --tag ${{ env.TAG_BASE }}:${{ env.PRERELEASE_LAMBDA_IMAGE_TAG }} \
            --file build_setup/Dockerfile \
            "${PWD}"
          docker tag ${{ env.TAG_BASE }}:${{ env.PRERELEASE_LAMBDA_IMAGE_TAG }} \
            ${{ env.TAG_BASE }}:latest-lambda-prerelease
          docker push ${{ env.TAG_BASE }}:${{ env.PRERELEASE_LAMBDA_IMAGE_TAG }}
          docker push ${{ env.TAG_BASE }}:latest-lambda-prerelease

      - name: Summarize Workflow Run
        run: |
          cat <<HEREDOC >>${GITHUB_STEP_SUMMARY}
          ## Successfully Pushed:

          - ${{ env.TAG_BASE }}:${{ env.PRERELEASE_IMAGE_TAG }}
          - ${{ env.TAG_BASE }}:latest-prerelease
          - ${{ env.TAG_BASE }}:${{ env.PRERELEASE_LAMBDA_IMAGE_TAG }}
          - ${{ env.TAG_BASE }}:latest-lambda-prerelease
          HEREDOC
