name: Publish Release
run-name: '@${{ github.triggering_actor }}: ${{ github.ref_name }}: ${{ github.event_name }}: ${{ github.event.action }}'
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: firetail-code-repository-scanner

jobs:
  publish-release:
    name: Publish Release
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:

      - name: Log In to the Container Registry
        run: |
           docker login ${{ env.REGISTRY }} \
            --username ${{ github.actor }} \
            --password-stdin <<<${{ secrets.GITHUB_TOKEN }}

      - name: Publish Prelease Lambda Image as Full Release
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-prerelease
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-prerelease \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-prerelease \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Publish Prelease Lambda Image as Full Release
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-lambda-prerelease
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-lambda-prerelease \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-lambda
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-lambda-prerelease \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-lambda
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-lambda
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-lambda

      - name: Summarize Workflow Run
        run: |
          cat <<HEREDOC >>${GITHUB_STEP_SUMMARY}
          ## Successfully Pushed:

          - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-lambda
          - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-lambda
          HEREDOC
