name: Pull Prerelease Image From ECR And Push As Release Image When Draft Release Is Published

on:
  release:
    types: [published]

env:
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 247286868737.dkr.ecr.eu-west-1.amazonaws.com
  ECR_REPOSITORY: firetail-github-scanner

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Pull prerelease image from ECR, retag it as a release, and push it back to ECR with the new tag
        id: build-image
        env:
          PRERELEASE_IMAGE_TAG: ${{ steps.get_release.outputs.tag_name }}-prerelease
          IMAGE_TAG: ${{ steps.get_release.outputs.tag_name }}
        run: |
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$PRERELEASE_IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$PRERELEASE_IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
