name: Pull Request CI

on:
  - pull_request

permissions:
  id-token: write
  contents: read

jobs:
  run-tests-in-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run Golang tests in Docker
        run: |
            DOCKER_BUILDKIT=1 docker build --target test-golang -t test-golang -f build_setup/Dockerfile .
            docker run --rm --entrypoint cat test-golang coverage.out > golang-coverage.out
            docker run --rm --entrypoint cat test-golang coverage.html > golang-coverage.html
      - uses: actions/upload-artifact@v3
        with:
            name: golang-coverage
            path: golang-coverage.*

      - name: Run Python tests in Docker
        run: |
          DOCKER_BUILDKIT=1 docker build --target test-python -t test-python -f build_setup/Dockerfile .
          docker run --rm --entrypoint cat test-python coverage.xml > python-coverage.xml
      - uses: actions/upload-artifact@v3
        with:
          name: python-coverage.xml
          path: python-coverage.xml

      - name: Run Python Lambda tests in Docker
        run: |
          DOCKER_BUILDKIT=1 docker build --target test-python-lambda -t test-python-lambda -f build_setup/Dockerfile .
          docker run --rm --entrypoint cat test-python-lambda coverage.xml > python-lambda-coverage.xml
      - uses: actions/upload-artifact@v3
        with:
          name: python-lambda-coverage.xml
          path: python-lambda-coverage.xml

      - uses: codecov/codecov-action@v3
        with:
          files: python-coverage.xml,golang-coverage.out
          flags: unittests
          fail_ci_if_error: false
          verbose: true